In [1]:
import numpy

In [3]:
import numpy as np

In [5]:
x = np.array([1, 2, 3, 4, 5, 6, 7])

In [6]:
type(x)

numpy.ndarray

In [7]:
x = np.random.rand(1000000)

In [10]:
%timeit sum(x)

68.7 ms ± 2.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%timeit x.sum()

198 µs ± 4.05 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
68000 / 198

343.4343434343434

In [13]:
x.mean()

0.49950975214922105

In [14]:
x.std()

0.2888078488509626

In [15]:
x

array([0.8564348 , 0.69128593, 0.24844516, ..., 0.90984822, 0.31536517,
       0.3098441 ])

In [17]:
y = x.reshape((1000,1000))

In [18]:
y.shape

(1000, 1000)

In [19]:
y.sum()

499509.7521492211

In [24]:
y[:, 0]

array([8.56434803e-01, 6.08296753e-01, 2.73524262e-01, 9.02696667e-03,
       9.36427173e-01, 7.26444045e-01, 4.52226920e-01, 7.34940479e-01,
       6.25871559e-01, 3.00848824e-01, 4.34129401e-01, 3.50869158e-01,
       3.03493098e-02, 5.98562231e-01, 4.62296732e-01, 2.79419301e-01,
       4.95654129e-01, 9.51508689e-01, 8.82742905e-01, 4.46224578e-01,
       2.87848953e-01, 8.14621632e-01, 8.60869327e-01, 5.51356832e-01,
       7.49411463e-01, 2.56258623e-01, 5.64253573e-01, 5.94922627e-01,
       1.76652036e-01, 5.30778990e-01, 6.06084891e-01, 5.97656224e-01,
       2.70161381e-02, 1.88415734e-01, 4.57678489e-01, 7.38486730e-01,
       4.78696404e-01, 4.66196960e-01, 4.43864999e-01, 2.89067276e-01,
       3.53523979e-01, 1.92121139e-01, 3.28942252e-01, 8.35942502e-01,
       8.85738808e-01, 9.07655556e-01, 3.46920620e-01, 4.77527254e-01,
       3.19665784e-02, 3.77085072e-01, 6.18485842e-01, 3.44460649e-01,
       8.88139402e-01, 2.93359579e-01, 2.25814014e-01, 6.79708309e-01,
      

In [26]:
y[0,:]

array([8.56434803e-01, 6.91285927e-01, 2.48445156e-01, 5.70648541e-01,
       4.17859421e-01, 5.49599773e-01, 3.51102885e-01, 2.05193813e-01,
       9.16425886e-01, 4.61569474e-01, 8.97834951e-01, 1.24768369e-01,
       8.16124891e-01, 4.10982477e-01, 6.54984611e-01, 1.78612206e-01,
       8.40550476e-01, 4.15488005e-01, 7.82275670e-01, 4.72842063e-01,
       6.03647957e-01, 2.71608929e-01, 2.49743162e-01, 7.20349901e-01,
       8.62638398e-02, 1.51726618e-02, 2.56600367e-01, 8.88080848e-01,
       2.69155409e-01, 6.60397229e-01, 4.79176012e-01, 9.05771640e-02,
       3.05293765e-01, 4.75679258e-01, 7.42658588e-01, 7.98078251e-01,
       1.15602877e-01, 6.34831733e-01, 7.62778858e-01, 8.41963129e-01,
       6.54411145e-01, 2.59439863e-01, 8.41722828e-01, 2.33081941e-01,
       5.51654246e-01, 7.98884451e-01, 3.63413807e-01, 5.82272960e-01,
       4.14380689e-01, 8.96110156e-01, 3.22680000e-01, 2.69663673e-01,
       1.11408053e-01, 2.09863112e-01, 8.47245453e-01, 6.71026702e-01,
      

In [34]:
y[:5,:5] 

array([[1.8564348 , 1.69128593, 1.24844516, 1.57064854, 1.41785942],
       [1.60829675, 1.00873123, 1.27611569, 1.71746352, 1.8887349 ],
       [1.27352426, 1.28587972, 1.56693958, 1.17348417, 1.23104982],
       [1.00902697, 1.39604142, 1.47169708, 1.89039683, 1.34476317],
       [1.93642717, 1.54035568, 1.64897707, 1.88686924, 1.68700433]])

In [33]:
y

array([[1.8564348 , 1.69128593, 1.24844516, ..., 0.75332286, 0.59902528,
        0.12457571],
       [1.60829675, 1.00873123, 1.27611569, ..., 0.96625078, 0.6247353 ,
        0.48357431],
       [1.27352426, 1.28587972, 1.56693958, ..., 0.7065363 , 0.48627872,
        0.27172418],
       ...,
       [0.24265695, 0.67136026, 0.22666124, ..., 0.12732591, 0.71197699,
        0.38953051],
       [0.16771904, 0.47034269, 0.45572697, ..., 0.2578362 , 0.80463845,
        0.41873842],
       [0.57997435, 0.95746594, 0.89197439, ..., 0.90984822, 0.31536517,
        0.3098441 ]])

In [35]:
import pandas

ModuleNotFoundError: No module named 'pandas'

In [36]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
  Using cached pandas-1.2.4-cp39-cp39-manylinux1_x86_64.whl (9.7 MB)
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Note: you may need to restart the kernel to use updated packages.


In [39]:
import pandas

In [40]:
import pandas as pd

In [42]:
affairs_df = pd.read_csv("https://raw.githubusercontent.com/mark-andrews/pysc01/master/data/affairs.csv")

In [43]:
affairs_df

affairs  gender   age  yearsmarried children  religiousness  education  \
0          0    male  37.0         10.00       no              3         18   
1          0  female  27.0          4.00       no              4         14   
2          0  female  32.0         15.00      yes              1         12   
3          0    male  57.0         15.00      yes              5         18   
4          0    male  22.0          0.75       no              2         17   
..       ...     ...   ...           ...      ...            ...        ...   
596        1    male  22.0          1.50      yes              1         12   
597        7  female  32.0         10.00      yes              2         18   
598        2    male  32.0         10.00      yes              2         17   
599        2    male  22.0          7.00      yes              3         18   
600        1  female  32.0         15.00      yes              3         14   

     occupation  rating  
0             7       4  
1             6       4  
2             1       4  
3             6       5  
4             6       3  
..          ...     ...  
596           2       5  
597           5       4  
598           6       5  
599           6       2  
600           1       5  

[601 rows x 9 columns]

In [44]:
type(affairs_df)

pandas.core.frame.DataFrame

In [48]:
affairs_df[['gender', 'children', 'age']]

gender children   age
0      male       no  37.0
1    female       no  27.0
2    female      yes  32.0
3      male      yes  57.0
4      male       no  22.0
..      ...      ...   ...
596    male      yes  22.0
597  female      yes  32.0
598    male      yes  32.0
599    male      yes  22.0
600  female      yes  32.0

[601 rows x 3 columns]

In [49]:
affairs_df[:10, ['gender', 'children', 'age']]

TypeError: '(slice(None, 10, None), ['gender', 'children', 'age'])' is an invalid key

In [51]:
affairs_df.iloc[:10, 2:5]

age  yearsmarried children
0  37.0         10.00       no
1  27.0          4.00       no
2  32.0         15.00      yes
3  57.0         15.00      yes
4  22.0          0.75       no
5  32.0          1.50       no
6  22.0          0.75       no
7  57.0         15.00      yes
8  32.0         15.00      yes
9  22.0          1.50       no

In [53]:
affairs_df.loc[[0, 4, 5], ['age', 'gender']]

age  gender
0  37.0    male
4  22.0    male
5  32.0  female